#!/usr/bin/env python3
"""Generate dvbs2_tables.h for the C DVB-S2 encoder.

Most tables are lifted straight out of dvbs2arm_1v30.s, so the C encoder is
guaranteed to use the same data as the assembly it replaces. The two LDPC
tables are not usable from there - the assembly fuses them into specialised
code paths - so those come from GNU Radio's gr-dtv (GPL-3.0), and the first
column of the assembly's ldpc_parameters_s34 was checked against
ldpc_tab_3_4S[0] to confirm they are the same tables.

Usage: gen_dvbs2_tables.py dvbs2arm_1v30.s dvb_ldpc_bb_impl.cc > dvbs2_tables.h
"""
import re, sys

def asm_table(src, label, kind):
    out, started = [], False
    for ln in src.split('\n'):
        if re.match(r'^%s:' % re.escape(label), ln):
            started = True
            ln = ln.split(':', 1)[1]
        elif not started:
            continue
        elif re.match(r'^[A-Za-z_][A-Za-z0-9_]*:', ln):
            break
        ln = ln.split('@:')[0]
        m = re.match(r'\s*\.(byte|word)\s+(.*)', ln)
        if m and m.group(1) == kind:
            for v in m.group(2).split(','):
                v = v.strip()
                if re.match(r'^(0x[0-9a-fA-F]+|\d+)$', v):
                    out.append(int(v, 0))
        elif started and ln.strip() and not ln.strip().startswith('.'):
            break
    if not out:
        sys.exit("table %s not found" % label)
    return out

def ldpc_table(src, name, rows):
    m = re.search(r'ldpc_tab_' + name + r'\[%d\]\[13\]\s*=\s*\{' % rows, src)
    if not m:
        sys.exit("ldpc table %s not found" % name)
    i, depth, buf = m.end(), 1, ''
    while depth:
        c = src[i]
        if c == '{': depth += 1
        elif c == '}': depth -= 1
        if depth: buf += c
        i += 1
    groups = re.findall(r'\{([^{}]*)\}', buf)
    return [[int(x) for x in re.findall(r'-?\d+', g)] for g in groups]

def emit(kind, name, vals, per):
    print("static const %s %s[%d] = {" % (kind, name, len(vals)))
    for i in range(0, len(vals), per):
        chunk = vals[i:i + per]
        fmt = "0x%02x" if kind == "uint8_t" else "0x%08x"
        print("\t" + ", ".join(fmt % v for v in chunk) + ",")
    print("};\n")

def main():
    asm = open(sys.argv[1]).read()
    gr = open(sys.argv[2]).read()
    print("/* Generated by gen_dvbs2_tables.py - do not edit. */")
    print("#ifndef DVBS2_TABLES_H\n#define DVBS2_TABLES_H\n#include <stdint.h>\n")
    emit("uint8_t", "crc8_table", asm_table(asm, 'crc8_table', 'byte'), 16)
    emit("uint32_t", "bbframe_scramble_words",
         asm_table(asm, 'bbframe_scramble_table', 'word'), 8)
    emit("uint32_t", "bch_s168_table", asm_table(asm, 'bch_s168_table', 'word'), 8)
    emit("uint8_t", "pl_scramble3", asm_table(asm, 'symbols_scramble_table3', 'byte'), 16)
    emit("uint8_t", "pl_scramble4", asm_table(asm, 'symbols_scramble_table4', 'byte'), 16)
    emit("uint32_t", "pl_header_s34_iq", asm_table(asm, 'PL_HEADER_S34_IQ', 'word'), 6)
    emit("uint32_t", "pl_header_s14_iq", asm_table(asm, 'PL_HEADER_S14_IQ', 'word'), 6)
    for name, rows in (("1_4S", 9), ("3_4S", 33)):
        t = ldpc_table(gr, name, rows)
        print("static const uint16_t ldpc_tab_%s[%d][13] = {" % (name, rows))
        for r in t:
            print("\t{ " + ", ".join(str(v) for v in r) + " },")
        print("};\n")
    print("#endif")

main()
